os:
  - linux

language: c
dist: trusty

compiler:
  - gcc

sudo: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - dc
      - binutils
      - cabextract
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - jq
      - gcc-4.8
      - g++-4.8

cache:
  - ccache
  - apt


script:
  - git clone --depth 1 https://github.com/radare/radare2.git
  - cd radare2
  - ./configure --prefix=`pwd`/install > /dev/null
  - make -s -j2 > /dev/null
  - make install > /dev/null
  - export PATH=${TRAVIS_BUILD_DIR}/radare2/install/bin:${PATH}
  - export PKG_CONFIG_PATH=${TRAVIS_BUILD_DIR}/radare2/pkgcfg:${PKG_CONFIG_PATH}
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/radare2/install/lib:${LD_LIBRARY_PATH}  
  - cd ..
  - pip install r2pipe
  - radare2 -v
  - chmod +x test.sh
  - ./test.sh